name: sadja_progress_stepper
description: "A customizable and scrollable progress stepper for Flutter applications."
version: 1.0.0
homepage: https://github.com/Sadja18/sadja_progress_stepper.git
repository: https://github.com/Sadja18/sadja_progress_stepper.git
issue_tracker: https://github.com/Sadja18/sadja_progress_stepper.git/issues

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: "Non linear steps: 01"
    path: example/screenshots/non-linear-stepper01.png
  
  - description: "Non linear steps: 02"
    path: example/screenshots/non-linear-stepper02.png

  - description: "Non linear steps: 03"
    path: example/screenshots/non-linear-stepper03.png

  - description: "Non linear steps: 04"
    path: example/screenshots/non-linear-stepper04-step-reset.png

  - description: "Linear steps with step reset: 01"
    path: example/screenshots/linear-stepper-with-step-reset01.png

  - description: "Linear steps with step reset: 02"
    path: example/screenshots/linear-stepper-with-step-reset02.png
