name: sadja_progress_stepper
description: "A customizable and scrollable progress stepper for Flutter applications."
version: 0.0.1
homepage: https://github.com/Sadja18/sadja_progress_stepper.git
repository: https://github.com/Sadja18/sadja_progress_stepper.git

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
